import { useMemo, useState } from 'react';
import {
  Activity, AlertTriangle, BadgeCheck, Banknote, BarChart3, BrainCircuit, CalendarCheck, CheckCircle2,
  ClipboardCheck, Database, Download, FileSpreadsheet, GitBranch, PackageCheck, ShieldCheck, Store,
  TestTube2, Truck, UploadCloud, Wallet, Wand2,
} from 'lucide-react';
import {
  buildAgingRows,
  buildApprovalInboxRows,
  buildDailyCloseRows,
  buildMenuEngineeringRows,
  buildRegressionRows,
  buildSettlementRows,
  buildTransferPlanRows,
  calcStockBalances,
} from '../engines/enterpriseAutopilotEngine';

type Locale = 'en' | 'ar';
type TabKey = 'command' | 'daily' | 'settlement' | 'inventory' | 'aging' | 'menu' | 'approvals' | 'workflow' | 'backend' | 'reports' | 'qa' | 'actions';

type Props = { state: any; totals?: any; update?: (fn: (current: any) => any, success?: string) => void; locale: Locale; notify?: (type: 'success' | 'warning' | 'error', message: string) => void; };

const L = (locale: Locale, en: string, ar: string) => locale === 'ar' ? ar : en;
const arr = (value: unknown): any[] => Array.isArray(value) ? value : [];
const num = (value: unknown) => Number(value || 0);
const today = () => new Date().toISOString().slice(0, 10);
const id = (prefix: string) => `${prefix}-${Math.random().toString(36).slice(2, 10)}`;

function money(value: number, locale: Locale) {
  return new Intl.NumberFormat(locale === 'ar' ? 'ar-SA' : 'en-US', { style: 'currency', currency: 'SAR', maximumFractionDigits: 2 }).format(Number.isFinite(value) ? value : 0);
}
function exportCsv(fileName: string, rows: Record<string, any>[]) {
  const safeRows = rows.length ? rows : [{ note: 'No rows' }];
  const headers = Array.from(safeRows.reduce((set, row) => { Object.keys(row).forEach((key) => set.add(key)); return set; }, new Set<string>()));
  const esc = (value: any) => `"${String(value ?? '').replace(/"/g, '""')}"`;
  const csv = [headers.join(','), ...safeRows.map((row) => headers.map((h) => esc(row[h])).join(','))].join('\n');
  const blob = new Blob(['\ufeff' + csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = fileName; a.click(); URL.revokeObjectURL(url);
}
function Pill({ tone, children }: { tone: string; children: any }) { const normalized = tone === 'good' || tone === 'ready' || tone === 'ok' ? 'good' : tone === 'bad' || tone === 'blocked' ? 'bad' : tone === 'warn' || tone === 'partial' ? 'warn' : 'info'; return <span className={`pill ${normalized}`}>{children}</span>; }
function Card({ title, icon, children, action }: { title: string; icon?: any; children: any; action?: any }) { return <section className="card v77-card"><div className="card-header"><div className="card-title">{icon}{title}</div>{action}</div>{children}</section>; }
function Kpi({ label, value, hint, icon, tone = 'info' }: { label: string; value: string; hint: string; icon?: any; tone?: 'good' | 'warn' | 'bad' | 'info' }) { return <div className={`kpi v77-kpi ${tone}`}><div className="kpi-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div></div>; }
function Table({ headers, rows }: { headers: any[]; rows: any[][] }) { return <div className="table-wrap"><table><thead><tr>{headers.map((h, i) => <th key={i}>{h}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, i) => <tr key={i}>{row.map((c, j) => <td key={j}>{c}</td>)}</tr>) : <tr><td colSpan={headers.length}><div className="empty">No rows</div></td></tr>}</tbody></table></div>; }

export default function EnterpriseAutopilotPage({ state, update, locale }: Props) {
  const [tab, setTab] = useState<TabKey>('command');
  const stockBalances = useMemo(() => calcStockBalances(state), [state]);
  const dailyClose = useMemo(() => buildDailyCloseRows(state, locale), [state, locale]);
  const settlement = useMemo(() => buildSettlementRows(state, locale), [state, locale]);
  const transferPlan = useMemo(() => buildTransferPlanRows(state, locale), [state, locale]);
  const aging = useMemo(() => buildAgingRows(state, locale), [state, locale]);
  const menuEngineering = useMemo(() => buildMenuEngineeringRows(state, locale), [state, locale]);
  const approvals = useMemo(() => buildApprovalInboxRows(state, locale), [state, locale]);
  const regression = useMemo(() => buildRegressionRows(locale), [locale]);
  const blockers = [...dailyClose.filter((r: any) => r.status === 'bad'), ...stockBalances.filter((r: any) => r.onHand < -0.0001).map((r: any) => ({ control: 'negative_stock', evidence: `${r.item.sku} @ ${r.store.code}` }))];
  const warnings = [...dailyClose.filter((r: any) => r.status === 'warn'), ...stockBalances.filter((r: any) => r.onHand > 0 && !r.avgCost).map((r: any) => ({ control: 'zero_cost_stock', evidence: `${r.item.sku} @ ${r.store.code}` })), ...approvals.map((r: any) => ({ control: 'pending_approval', evidence: r.ref }))];
  const readiness = Math.max(0, Math.min(100, 100 - blockers.length * 15 - warnings.length * 4));
  const inventoryValue = stockBalances.reduce((s: number, r: any) => s + num(r.value), 0);
  const apOpen = aging.reduce((s: number, r: any) => s + num(r.balance), 0);
  const highMargin = menuEngineering.filter((r: any) => num(r.marginPct) >= 60).length;
  const tabs: [TabKey, string, any][] = [
    ['command', L(locale, 'Command Board', 'لوحة القيادة'), <BrainCircuit size={16}/>], ['daily', L(locale, 'Daily Close', 'الإغلاق اليومي'), <CalendarCheck size={16}/>], ['settlement', L(locale, 'Settlement', 'التسويات'), <Banknote size={16}/>], ['inventory', L(locale, 'Inventory Autopilot', 'مساعد المخزون'), <Store size={16}/>], ['aging', L(locale, 'AP / Cash Forecast', 'الدائنون / توقع النقد'), <Wallet size={16}/>], ['menu', L(locale, 'Menu Engineering', 'هندسة القائمة'), <BarChart3 size={16}/>], ['approvals', L(locale, 'Approval Inbox', 'صندوق الاعتمادات'), <ShieldCheck size={16}/>], ['workflow', L(locale, 'Workflow Automation', 'أتمتة الإجراءات'), <GitBranch size={16}/>], ['backend', L(locale, 'Backend Sprint', 'سباق الخلفية'), <Database size={16}/>], ['reports', L(locale, 'Report Factory', 'مصنع التقارير'), <FileSpreadsheet size={16}/>], ['qa', L(locale, 'QA Regression', 'اختبار الانحدار'), <TestTube2 size={16}/>], ['actions', L(locale, 'Safe Actions', 'إجراءات آمنة'), <Wand2 size={16}/>],
  ];
  const exportAll = () => exportCsv(`v77_autopilot_control_pack_${today()}.csv`, [...dailyClose.map((r: any) => ({ section: 'daily_close', ...r })), ...settlement.map((r: any) => ({ section: 'settlement', ...r })), ...transferPlan.map((r: any) => ({ section: 'inventory_transfer_plan', ...r })), ...aging.map((r: any) => ({ section: 'ap_aging', ...r })), ...menuEngineering.map((r: any) => ({ section: 'menu_engineering', ...r })), ...approvals.map((r: any) => ({ section: 'approval_inbox', ...r })), ...regression.map((r: any) => ({ section: 'qa_regression', ...r }))]);
  const addAudit = (action: string, note: string) => { if (!update) return; update((current: any) => ({ ...current, audits: [...arr(current.audits), { id: id('AUD'), at: new Date().toISOString(), action, entity: 'enterprise_autopilot_v77', ref: `V77-${today()}`, user: 'Local Admin', note }] }), L(locale, 'Autopilot audit note saved', 'تم حفظ ملاحظة تدقيق المساعد')); };
  const createNextPeriod = () => { if (!update) return; update((current: any) => { const now = new Date(); const start = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().slice(0, 10); const end = new Date(now.getFullYear(), now.getMonth() + 1, 0).toISOString().slice(0, 10); const code = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`; if (arr(current.fiscalPeriods).some((p: any) => p.code === code)) return current; return { ...current, fiscalPeriods: [...arr(current.fiscalPeriods), { id: id('PER'), code, nameEn: `Period ${code}`, nameAr: `فترة ${code}`, startDate: start, endDate: end, status: 'open' }] }; }, L(locale, 'Current fiscal period created', 'تم إنشاء الفترة الحالية')); };
  const seedAutomationPolicies = () => { if (!update) return; update((current: any) => ({ ...current, importProfiles: [...arr(current.importProfiles), { id: id('IMP'), name: 'Foodics Monthly Sales Auto Profile', importType: 'foodics_sales_bundle', fileType: 'csv', mappings: { sku: 'sku', order_reference: 'order_reference', payment_method_name: 'payment_method_name' }, duplicateKey: 'business_date+order_reference', requiresApproval: true }], audits: [...arr(current.audits), { id: id('AUD'), at: new Date().toISOString(), action: 'v77_seed_automation_profile', entity: 'import_profile', ref: 'Foodics Monthly Sales Auto Profile', user: 'Local Admin', note: 'Seeded Foodics import profile with approval requirement.' }] }), L(locale, 'Foodics automation profile seeded', 'تم إنشاء ملف أتمتة فودكس')); };

  return <div className="page-grid v77-workspace">
    <div className="v77-hero"><div><span className="eyebrow">v68-v77 Mega Bundle</span><h2>{L(locale, 'Enterprise Autopilot Suite', 'جناح المساعد المؤسسي')}</h2><p>{L(locale, 'Ten combined upgrades for daily close, settlement, inventory planning, AP forecast, menu engineering, approvals, workflow automation, backend sprint, board reports and QA regression.', 'عشر ترقيات مجمعة للإغلاق اليومي، التسويات، تخطيط المخزون، توقع الدائنين، هندسة القائمة، الاعتمادات، أتمتة الإجراءات، سباق الخلفية، تقارير الإدارة، واختبار الانحدار.')}</p></div><div className="v77-score"><strong>{readiness}%</strong><span>{L(locale, 'Autopilot readiness', 'جاهزية المساعد')}</span><Pill tone={readiness >= 80 ? 'good' : readiness >= 60 ? 'warn' : 'bad'}>{readiness >= 80 ? L(locale, 'Strong', 'قوي') : readiness >= 60 ? L(locale, 'Review', 'مراجعة') : L(locale, 'Blocked', 'محجوب')}</Pill></div></div>
    <div className="kpi-grid"><Kpi label={L(locale, 'Readiness', 'الجاهزية')} value={`${readiness}%`} hint={L(locale, 'Blockers and warnings weighted', 'حسب العوائق والتحذيرات')} icon={<BadgeCheck/>} tone={readiness >= 80 ? 'good' : readiness >= 60 ? 'warn' : 'bad'} /><Kpi label={L(locale, 'Inventory Value', 'قيمة المخزون')} value={money(inventoryValue, locale)} hint={L(locale, 'Stock balance × average cost', 'الرصيد × متوسط التكلفة')} icon={<PackageCheck/>} tone="info" /><Kpi label={L(locale, 'Open AP', 'الدائنون المفتوحون')} value={money(apOpen, locale)} hint={L(locale, 'Invoice-allocated preview', 'معاينة حسب الفواتير')} icon={<Wallet/>} tone={apOpen ? 'warn' : 'good'} /><Kpi label={L(locale, 'High Margin Items', 'أصناف عالية الهامش')} value={`${highMargin}`} hint={L(locale, 'Menu engineering preview', 'معاينة هندسة القائمة')} icon={<BarChart3/>} tone="good" /></div>
    <div className="tab-row v77-tabs">{tabs.map(([key, label, icon]) => <button key={key} className={tab === key ? 'active-tab' : ''} onClick={() => setTab(key)}>{icon}{label}</button>)}</div>
    {tab === 'command' && <div className="page-grid two"><Card title={L(locale, 'Autopilot command board', 'لوحة قيادة المساعد')} icon={<Activity/>} action={<button onClick={exportAll}><Download size={16}/>{L(locale, 'Export control pack', 'تصدير حزمة الرقابة')}</button>}><div className="v77-metric-list"><div><span>{L(locale, 'Critical blockers', 'عوائق حرجة')}</span><strong>{blockers.length}</strong></div><div><span>{L(locale, 'Warnings', 'تحذيرات')}</span><strong>{warnings.length}</strong></div><div><span>{L(locale, 'Pending approvals', 'اعتمادات معلقة')}</span><strong>{approvals.length}</strong></div><div><span>{L(locale, 'Menu items reviewed', 'أصناف قائمة مراجعة')}</span><strong>{menuEngineering.length}</strong></div><div><span>{L(locale, 'Stock balance rows', 'صفوف أرصدة المخزون')}</span><strong>{stockBalances.length}</strong></div><div><span>{L(locale, 'Settlement rows', 'صفوف التسوية')}</span><strong>{settlement.length}</strong></div></div><div className="notice">{L(locale, 'This suite is a local-control layer. It does not replace Supabase/server-side posting yet, but it makes the prototype easier to control and test.', 'هذا الجناح طبقة رقابة محلية. لا يستبدل خلفية Supabase أو الترحيل من الخادم بعد، لكنه يجعل النموذج أسهل للتحكم والاختبار.')}</div></Card><Card title={L(locale, 'Top required actions', 'أهم الإجراءات المطلوبة')} icon={<AlertTriangle/>}><Table headers={[L(locale, 'Type', 'النوع'), L(locale, 'Evidence', 'الدليل'), L(locale, 'Priority', 'الأولوية')]} rows={[...blockers.map((b: any) => ['Blocker', b.evidence || b.control, <Pill tone="bad">P0</Pill>]), ...warnings.slice(0, 8).map((w: any) => ['Warning', w.evidence || w.control, <Pill tone="warn">P1</Pill>])]}/></Card></div>}
    {tab === 'daily' && <Card title={L(locale, 'Daily close checklist', 'قائمة الإغلاق اليومي')} icon={<CalendarCheck/>} action={<button onClick={() => exportCsv(`v77_daily_close_${today()}.csv`, dailyClose)}><Download size={16}/>{L(locale, 'Export', 'تصدير')}</button>}><Table headers={[L(locale, 'Control', 'الضابط'), L(locale, 'Status', 'الحالة'), L(locale, 'Evidence', 'الدليل'), L(locale, 'Next step', 'الخطوة التالية')]} rows={dailyClose.map((r: any) => [r.control, <Pill tone={r.status}>{r.status}</Pill>, r.evidence, r.next])}/></Card>}
    {tab === 'settlement' && <Card title={L(locale, 'Foodics / POS settlement workbench', 'منصة تسوية فودكس / نقاط البيع')} icon={<Banknote/>} action={<button onClick={() => exportCsv(`v77_settlement_${today()}.csv`, settlement)}><Download size={16}/>{L(locale, 'Export', 'تصدير')}</button>}><Table headers={[L(locale, 'Method / Control', 'طريقة / ضابط'), L(locale, 'Source', 'المصدر'), L(locale, 'Expected', 'المتوقع'), L(locale, 'Account', 'الحساب'), L(locale, 'Control', 'الضابط'), L(locale, 'Status', 'الحالة')]} rows={settlement.map((r: any) => [r.method, r.source, r.expected, r.account, r.control, <Pill tone={r.status}>{r.status}</Pill>])}/></Card>}
    {tab === 'inventory' && <div className="page-grid two"><Card title={L(locale, 'Inventory transfer and reorder autopilot', 'مساعد التحويل وإعادة الطلب')} icon={<Truck/>} action={<button onClick={() => exportCsv(`v77_inventory_transfer_plan_${today()}.csv`, transferPlan)}><Download size={16}/>{L(locale, 'Export plan', 'تصدير الخطة')}</button>}><Table headers={[L(locale, 'Item', 'الصنف'), 'SKU', L(locale, 'Target store', 'المخزن الهدف'), L(locale, 'Current', 'الحالي'), L(locale, 'Min', 'الحد الأدنى'), L(locale, 'Suggested source', 'المصدر المقترح'), L(locale, 'Suggested qty', 'الكمية المقترحة'), L(locale, 'Status', 'الحالة')]} rows={transferPlan.map((r: any) => [r.item, r.sku, r.targetStore, r.currentQty, r.minStock, r.suggestedSource, r.suggestedQty, r.status])}/></Card><Card title={L(locale, 'Inventory risk rows', 'صفوف مخاطر المخزون')} icon={<Store/>}><Table headers={[L(locale, 'Store', 'المخزن'), 'SKU', L(locale, 'Item', 'الصنف'), L(locale, 'On hand', 'الرصيد'), L(locale, 'Avg cost', 'متوسط التكلفة'), L(locale, 'Value', 'القيمة'), L(locale, 'Risk', 'الخطر')]} rows={stockBalances.filter((r: any) => r.onHand < 0 || (r.onHand > 0 && !r.avgCost)).map((r: any) => [r.store.nameEn || r.store.code, r.item.sku, r.item.nameEn, r.onHand, money(r.avgCost, locale), money(r.value, locale), <Pill tone={r.onHand < 0 ? 'bad' : 'warn'}>{r.onHand < 0 ? 'negative' : 'zero-cost'}</Pill>])}/></Card></div>}
    {tab === 'aging' && <Card title={L(locale, 'AP aging and cash forecast preview', 'معاينة أعمار الدائنين وتوقع النقد')} icon={<Wallet/>} action={<button onClick={() => exportCsv(`v77_ap_aging_${today()}.csv`, aging)}><Download size={16}/>{L(locale, 'Export AP aging', 'تصدير أعمار الدائنين')}</button>}><Table headers={[L(locale, 'Type', 'النوع'), L(locale, 'Ref', 'المرجع'), L(locale, 'Party', 'الطرف'), L(locale, 'Date', 'التاريخ'), L(locale, 'Total', 'الإجمالي'), L(locale, 'Paid', 'المدفوع'), L(locale, 'Balance', 'الرصيد'), L(locale, 'Bucket', 'الفئة'), L(locale, 'Risk', 'المخاطر')]} rows={aging.map((r: any) => [r.type, r.ref, r.party, r.date, money(r.total, locale), money(r.paid, locale), money(r.balance, locale), r.bucket, r.risk])}/></Card>}
    {tab === 'menu' && <Card title={L(locale, 'Menu engineering preview', 'معاينة هندسة القائمة')} icon={<BarChart3/>} action={<button onClick={() => exportCsv(`v77_menu_engineering_${today()}.csv`, menuEngineering)}><Download size={16}/>{L(locale, 'Export', 'تصدير')}</button>}><Table headers={[L(locale, 'Code', 'الكود'), L(locale, 'Item', 'الصنف'), L(locale, 'Sold qty', 'الكمية المباعة'), L(locale, 'Net price', 'السعر الصافي'), L(locale, 'Recipe cost', 'تكلفة الوصفة'), L(locale, 'Margin', 'الهامش'), L(locale, 'Margin %', 'نسبة الهامش'), L(locale, 'Class', 'التصنيف')]} rows={menuEngineering.map((r: any) => [r.code, r.item, r.soldQty, money(r.priceNet, locale), money(r.recipeCost, locale), money(r.margin, locale), `${num(r.marginPct).toFixed(1)}%`, r.classification])}/></Card>}
    {tab === 'approvals' && <Card title={L(locale, 'Approval inbox and maker-checker board', 'صندوق الاعتمادات ومبدأ المدخل والمراجع')} icon={<ShieldCheck/>} action={<button onClick={() => exportCsv(`v77_approval_inbox_${today()}.csv`, approvals)}><Download size={16}/>{L(locale, 'Export', 'تصدير')}</button>}><Table headers={[L(locale, 'Module', 'الوحدة'), L(locale, 'Reference', 'المرجع'), L(locale, 'Type', 'النوع'), L(locale, 'Status', 'الحالة'), L(locale, 'Risk/value', 'القيمة/المخاطر'), L(locale, 'Next action', 'الإجراء التالي')]} rows={approvals.map((r: any) => [r.module, r.ref, r.type, <Pill tone={r.status === 'pending' || r.status === 'draft' ? 'warn' : 'info'}>{r.status}</Pill>, r.risk, r.next])}/></Card>}
    {tab === 'workflow' && <div className="page-grid two"><Card title={L(locale, 'Workflow automation plan', 'خطة أتمتة الإجراءات')} icon={<GitBranch/>}><ol className="v77-ordered"><li>{L(locale, 'Foodics batch: Uploaded -> Mapped -> Validated -> Approved -> Posted -> Reversed/Closed.', 'دفعة فودكس: مرفوعة ← مطابقة ← محققة ← معتمدة ← مرحلة ← معكوسة/مغلقة.')}</li><li>{L(locale, 'Stock count: Draft sheet -> Count uploaded -> Variance review -> Approved -> Posted -> Period locked.', 'الجرد: كشف مسودة ← رفع الجرد ← مراجعة الفرق ← اعتماد ← ترحيل ← قفل الفترة.')}</li><li>{L(locale, 'Purchasing: Request -> PO -> GRN -> Invoice match -> Payment run -> Supplier statement.', 'المشتريات: طلب ← أمر شراء ← استلام ← مطابقة فاتورة ← دفعة ← كشف مورد.')}</li><li>{L(locale, 'Finance: Draft journal -> Review -> Post -> Reverse with reason only.', 'المالية: قيد مسودة ← مراجعة ← ترحيل ← عكس بسبب فقط.')}</li></ol></Card><Card title={L(locale, 'Document lifecycle gaps', 'فجوات دورة المستند')} icon={<ClipboardCheck/>}><Table headers={[L(locale, 'Document', 'المستند'), L(locale, 'Current need', 'الاحتياج الحالي'), L(locale, 'Priority', 'الأولوية')]} rows={[['Foodics batch', L(locale, 'Backend persisted status and row-level posting evidence', 'حالة محفوظة بالخلفية وأدلة ترحيل على مستوى الصف'), <Pill tone="bad">P0</Pill>], ['Stock count', L(locale, 'Count lifecycle and period lock enforcement', 'دورة الجرد وفرض قفل الفترة'), <Pill tone="bad">P0</Pill>], ['Payment voucher', L(locale, 'Multi-invoice allocation and PDF voucher', 'توزيع على عدة فواتير وسند PDF'), <Pill tone="warn">P1</Pill>], ['Recipe version', L(locale, 'Approval + effective date before cost changes', 'اعتماد + تاريخ سريان قبل تغيير التكلفة'), <Pill tone="warn">P1</Pill>]]}/></Card></div>}
    {tab === 'backend' && <Card title={L(locale, 'Supabase sprint board', 'لوحة سباق Supabase')} icon={<Database/>}><Table headers={[L(locale, 'Sprint', 'السباق'), L(locale, 'Deliverable', 'المخرج'), L(locale, 'Why it matters', 'الأهمية'), L(locale, 'Status', 'الحالة')]} rows={[[ 'S1', 'Auth + profiles + branches/stores scopes', L(locale, 'Real users and location security', 'مستخدمون حقيقيون وأمان نطاق المواقع'), <Pill tone="bad">Missing</Pill>], ['S2', 'Master data tables + RLS', L(locale, 'Stop relying on localStorage for setup', 'إيقاف الاعتماد على التخزين المحلي للإعداد'), <Pill tone="bad">Missing</Pill>], ['S3', 'Foodics import staging tables', L(locale, 'Persist large files and mappings safely', 'حفظ الملفات الكبيرة والمطابقات بأمان'), <Pill tone="bad">Missing</Pill>], ['S4', 'Server-side posting Edge Functions', L(locale, 'Protect GL/inventory posting from browser manipulation', 'حماية ترحيل القيود والمخزون من التلاعب'), <Pill tone="bad">Missing</Pill>], ['S5', 'Storage buckets + audit triggers', L(locale, 'Invoices, GRN, payments and immutable logs', 'الفواتير والاستلام والمدفوعات وسجلات غير قابلة للتلاعب'), <Pill tone="warn">Designed</Pill>]]}/></Card>}
    {tab === 'reports' && <Card title={L(locale, 'Board-grade report factory', 'مصنع تقارير الإدارة العليا')} icon={<FileSpreadsheet/>}><Table headers={[L(locale, 'Report', 'التقرير'), L(locale, 'Purpose', 'الهدف'), L(locale, 'Format', 'الصيغة'), L(locale, 'Priority', 'الأولوية')]} rows={[[ 'Executive Board Pack', L(locale, 'Owner/CEO monthly performance', 'أداء شهري للمالك/الرئيس التنفيذي'), 'PDF + Excel', <Pill tone="bad">P0</Pill>], ['Foodics Settlement Pack', L(locale, 'Cash/MADA/delivery/internal settlement', 'تسوية النقد/مدى/التطبيقات/الداخلي'), 'Excel', <Pill tone="bad">P0</Pill>], ['Theoretical vs Actual Food Cost', L(locale, 'Control recipe demand vs stock count variance', 'رقابة طلب الوصفة مقابل فروقات الجرد'), 'Dashboard + Excel', <Pill tone="bad">P0</Pill>], ['Branch P&L by Month', L(locale, 'Profitability by restaurant', 'ربحية كل مطعم'), 'Excel + charts', <Pill tone="warn">P1</Pill>], ['Purchase Price Variance', L(locale, 'Supplier price control', 'رقابة أسعار الموردين'), 'Excel', <Pill tone="warn">P1</Pill>]]}/></Card>}
    {tab === 'qa' && <Card title={L(locale, 'QA regression suite', 'حزمة اختبار الانحدار')} icon={<TestTube2/>} action={<button onClick={() => exportCsv(`v77_qa_regression_${today()}.csv`, regression)}><Download size={16}/>{L(locale, 'Export QA', 'تصدير الاختبار')}</button>}><Table headers={[L(locale, 'Test', 'الاختبار'), L(locale, 'Steps', 'الخطوات'), L(locale, 'Expected result', 'النتيجة المتوقعة'), L(locale, 'Priority', 'الأولوية')]} rows={regression.map((r: any) => [r.test, r.steps, r.expected, <Pill tone={r.priority === 'P0' ? 'bad' : 'warn'}>{r.priority}</Pill>])}/></Card>}
    {tab === 'actions' && <Card title={L(locale, 'Safe local actions', 'إجراءات محلية آمنة')} icon={<Wand2/>}><div className="button-row"><button onClick={exportAll}><Download size={16}/>{L(locale, 'Export full v77 control pack', 'تصدير حزمة v77 الكاملة')}</button><button onClick={() => addAudit('v77_health_review', `Autopilot readiness ${readiness}%, blockers ${blockers.length}, warnings ${warnings.length}.`)}><CheckCircle2 size={16}/>{L(locale, 'Log health review', 'تسجيل مراجعة الصحة')}</button><button onClick={createNextPeriod}><CalendarCheck size={16}/>{L(locale, 'Create current period', 'إنشاء الفترة الحالية')}</button><button onClick={seedAutomationPolicies}><UploadCloud size={16}/>{L(locale, 'Seed Foodics automation profile', 'إنشاء ملف أتمتة فودكس')}</button></div><div className="notice"><strong>{L(locale, 'Safety note:', 'ملاحظة أمان:')}</strong> {L(locale, 'These actions only add local trial data or audit notes. They do not post finance or inventory transactions silently.', 'هذه الإجراءات تضيف بيانات تجريبية أو ملاحظات تدقيق فقط. لا ترحّل قيودًا مالية أو حركات مخزون بصمت.')}</div></Card>}
  </div>;
}
