import { useMemo, useState, type ReactNode } from 'react';
import { AlertTriangle, CheckCircle2, ClipboardCheck, Database, Download, Gauge, Rocket, ShieldCheck, Sparkles, Table2, Wrench } from 'lucide-react';
import { buildV299PreFinalNotes, buildV299RegressionSuite, buildV299ReleaseGates, buildV299Snapshot, rowsToCsv } from '../engines/enterpriseV299Engine';

type Locale = 'en' | 'ar';
type Props = { state: any; totals: any; update: (fn: (s: any) => any, success?: string) => void; locale: Locale; notify: (type: 'success' | 'warning' | 'error', message: string) => void };
const L = (locale: Locale, en: string, ar: string) => locale === 'ar' ? ar : en;
const money = (value: number, locale: Locale) => new Intl.NumberFormat(locale === 'ar' ? 'ar-SA' : 'en-US', { style: 'currency', currency: 'SAR', maximumFractionDigits: 2 }).format(Number(value || 0));
function downloadCsv(filename: string, csv: string) { const blob = new Blob(['\ufeff' + csv], { type: 'text/csv;charset=utf-8;' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }
function downloadJson(filename: string, data: unknown) { const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json;charset=utf-8;' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }
function Card({ title, icon, children, action }: { title: string; icon?: ReactNode; children: ReactNode; action?: ReactNode }) { return <section className="v240-card"><div className="v240-card-head"><div className="v240-title">{icon}<h3>{title}</h3></div>{action}</div>{children}</section>; }
function KPI({ label, value, hint, icon }: { label: string; value: string | number; hint: string; icon: ReactNode }) { return <div className="v240-kpi"><div className="v240-kpi-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div></div>; }
function Badge({ children, tone = 'info' }: { children: ReactNode; tone?: 'ready' | 'warn' | 'bad' | 'info' }) { return <span className={`v240-badge ${tone}`}>{children}</span>; }
function Table({ rows }: { rows: Array<Record<string, any>> }) { if (!rows.length) return <div className="notice">No rows</div>; const headers = Array.from(rows.reduce((set, row) => { Object.keys(row || {}).forEach((key) => set.add(key)); return set; }, new Set<string>())); return <div className="v240-table"><table><thead><tr>{headers.map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row, idx) => <tr key={idx}>{headers.map((h) => <td key={h}>{typeof row?.[h] === 'string' && ['ready','warning','blocked'].includes(row[h]) ? <Badge tone={row[h] === 'ready' ? 'ready' : row[h] === 'blocked' ? 'bad' : 'warn'}>{row[h]}</Badge> : String(row?.[h] ?? '')}</td>)}</tr>)}</tbody></table></div>; }
const tabs = ['command', 'gates', 'scorecard', 'regression', 'issues', 'production', 'final-notes', 'actions'] as const;
type Tab = typeof tabs[number];

export default function EnterpriseV299Page({ state, totals, update, locale, notify }: Props) {
  const [tab, setTab] = useState<Tab>('command');
  const snapshot = useMemo(() => buildV299Snapshot(state, totals), [state, totals]);
  const gates = useMemo(() => buildV299ReleaseGates(snapshot), [snapshot]);
  const qa = useMemo(() => buildV299RegressionSuite(snapshot), [snapshot]);
  const notes = useMemo(() => buildV299PreFinalNotes(snapshot), [snapshot]);
  const exportAll = () => downloadCsv('v299_pre_final_release_candidate_pack.csv', rowsToCsv([
    { section: 'score', ...snapshot.scores },
    ...gates.map((r) => ({ section: 'release_gate', ...r })),
    ...qa.map((r) => ({ section: 'qa', ...r })),
    ...snapshot.issues.map((r: any) => ({ section: 'issue', ...r })),
    ...notes.map((r) => ({ section: 'note', ...r })),
  ]));
  const logReview = () => update((s: any) => ({ ...s, audits: [...(Array.isArray(s.audits) ? s.audits : []), { id: `AUD-${Date.now()}`, at: new Date().toISOString(), action: 'v299.pre_final_review', entity: 'release_candidate', ref: 'V299', user: 'Local Admin', note: `Pre-final review logged. Local score ${snapshot.scores.localTrial}/100, production ${snapshot.scores.productionReadiness}/100.` }] }), L(locale, 'v299 pre-final review logged', 'تم تسجيل مراجعة v299 قبل النهائي'));
  const ensureFinalPilot = () => update((s: any) => {
    const periods = Array.isArray(s.fiscalPeriods) ? s.fiscalPeriods : [];
    const permissions = Array.isArray(s.permissions) ? s.permissions : [];
    const needed = ['release.pre_final.review', 'pilot.evidence.export', 'backend.cutover.prepare', 'posting.guard.override_request'];
    const existing = new Set(permissions.map((p: any) => p.key));
    const newPerms = needed.filter((key) => !existing.has(key)).map((key) => ({ key, moduleEn: 'Enterprise Release', moduleAr: 'إطلاق المؤسسة', labelEn: key, labelAr: key }));
    const nextPeriods = periods.some((p: any) => p.code === 'PILOT-FINAL') ? periods : [...periods, { id: `PER-${Date.now()}`, code: 'PILOT-FINAL', name: 'Pre-final pilot period', startDate: '2026-04-01', endDate: '2026-04-30', status: 'open' }];
    return { ...s, permissions: [...permissions, ...newPerms], fiscalPeriods: nextPeriods, audits: [...(Array.isArray(s.audits) ? s.audits : []), { id: `AUD-${Date.now()+1}`, at: new Date().toISOString(), action: 'v299.ensure_pre_final_pilot', entity: 'release_candidate', ref: 'V299', user: 'Local Admin', note: `Added ${newPerms.length} release permissions and ensured pre-final pilot period.` }] };
  }, L(locale, 'Pre-final pilot controls ensured', 'تم تجهيز ضوابط تجربة ما قبل النهائي'));

  return <div className="v240-page">
    <div className="v240-hero"><div><span className="eyebrow">v299 Pre-Final Release Candidate</span><h2>{L(locale, 'Patch before final — safe freeze candidate', 'التحديث قبل النهائي — مرشح تجميد آمن')}</h2><p>{L(locale, 'This version is intentionally conservative: stability, release gates, QA evidence, honest scoring, and pilot controls before the final production patch.', 'هذا الإصدار محافظ عمداً: استقرار، بوابات إطلاق، أدلة جودة، تقييم صريح، وضوابط تجربة قبل التحديث النهائي للإنتاج.')}</p></div><div className="v240-score"><span>{L(locale, 'Local pilot score', 'درجة التجربة المحلية')}</span><strong>{snapshot.scores.localTrial}%</strong><small>{snapshot.blockers.length ? L(locale, 'Fix blockers before final freeze', 'حل العوائق قبل التجميد النهائي') : L(locale, 'Pre-final candidate looks clean', 'مرشح ما قبل النهائي يبدو جيداً')}</small></div></div>
    <div className="v240-tabs">{tabs.map((t) => <button key={t} className={tab === t ? 'active' : ''} onClick={() => setTab(t)}>{tabLabel(t, locale)}</button>)}</div>
    {tab === 'command' && <div className="v240-grid"><Card title={L(locale, 'Pre-final command board', 'لوحة قيادة ما قبل النهائي')} icon={<Gauge/>} action={<button onClick={exportAll}><Download size={16}/>{L(locale, 'Export pre-final pack', 'تصدير حزمة ما قبل النهائي')}</button>}><div className="v240-kpi-grid"><KPI label={L(locale, 'Local pilot', 'التجربة المحلية')} value={`${snapshot.scores.localTrial}%`} hint={L(locale, 'Can approach 10 only after QA passes', 'تقترب من 10 بعد اجتياز QA')} icon={<CheckCircle2/>}/><KPI label={L(locale, 'Production readiness', 'جاهزية الإنتاج')} value={`${snapshot.scores.productionReadiness}%`} hint={L(locale, 'Cannot honestly be 10 before live backend pilot', 'لا يمكن جعلها 10 بصدق قبل تجربة خلفية حية')} icon={<AlertTriangle/>}/><KPI label={L(locale, 'Backend/security', 'الخلفية والأمان')} value={`${snapshot.scores.backendSecurity}%`} hint={L(locale, 'Scaffolded, not fully live', 'مجهزة ولم تربط بالكامل')} icon={<Database/>}/><KPI label={L(locale, 'Inventory value', 'قيمة المخزون')} value={money(snapshot.finance.inventoryValue, locale)} hint={`${snapshot.counts.stockMovements} movements`} icon={<Table2/>}/></div><div className="v240-alerts"><h4>{L(locale, 'Current release issues', 'ملاحظات الإصدار الحالية')}</h4>{snapshot.issues.slice(0, 12).map((row: any, i: number) => <div className={`v240-issue ${row.severity === 'critical' ? 'critical' : row.severity === 'warning' ? 'warning' : ''}`} key={i}><strong>{row.severity}</strong><span>{row.area}: {row.finding}</span><small>{row.fix}</small></div>)}</div></Card><Card title={L(locale, 'Operating snapshot', 'لقطة التشغيل')} icon={<ClipboardCheck/>}><Table rows={[snapshot.counts, snapshot.finance]}/></Card></div>}
    {tab === 'gates' && <Card title={L(locale, 'Release gates before final patch', 'بوابات الإطلاق قبل التحديث النهائي')} icon={<ShieldCheck/>} action={<button onClick={() => downloadCsv('v299_release_gates.csv', rowsToCsv(gates))}><Download size={16}/>{L(locale, 'Export gates', 'تصدير البوابات')}</button>}><Table rows={gates}/></Card>}
    {tab === 'scorecard' && <Card title={L(locale, 'Honest scorecard', 'التقييم الصريح')} icon={<Sparkles/>}><div className="v240-kpi-grid"><KPI label="Local MVP / prototype" value={`${snapshot.scores.localTrial}/100`} hint="Strong local testing candidate" icon={<CheckCircle2/>}/><KPI label="Serious ERP foundation" value={`${snapshot.scores.seriousFoundation}/100`} hint="Strong architecture and workflows" icon={<Rocket/>}/><KPI label="Enterprise direction" value={`${snapshot.scores.enterpriseDirection}/100`} hint="Very strong direction" icon={<Sparkles/>}/><KPI label="Production readiness" value={`${snapshot.scores.productionReadiness}/100`} hint="Not 100 until backend live-tested" icon={<Database/>}/></div><div className="notice">{L(locale, 'I will not fake a 10/10 production score. This is a pre-final candidate. A true 10 requires live Supabase Auth/RLS, server-side posting, file storage, pilot testing, and signed-off financial/inventory reconciliation.', 'لن أضع 10/10 للإنتاج بشكل غير حقيقي. هذا مرشح ما قبل النهائي. الدرجة 10 الحقيقية تحتاج Auth/RLS في Supabase وترحيل خادمي وتخزين ملفات وتجربة فعلية ومطابقة مالية ومخزنية معتمدة.')}</div></Card>}
    {tab === 'regression' && <Card title={L(locale, 'Pre-final regression suite', 'اختبارات ما قبل النهائي')} icon={<ClipboardCheck/>} action={<button onClick={() => downloadCsv('v299_regression_suite.csv', rowsToCsv(qa))}><Download size={16}/>{L(locale, 'Export QA', 'تصدير QA')}</button>}><Table rows={qa}/></Card>}
    {tab === 'issues' && <Card title={L(locale, 'Issue and repair queue', 'قائمة المشاكل والإصلاح')} icon={<Wrench/>} action={<button onClick={() => downloadCsv('v299_issue_queue.csv', rowsToCsv(snapshot.issues))}><Download size={16}/>{L(locale, 'Export issues', 'تصدير المشاكل')}</button>}><Table rows={snapshot.issues}/></Card>}
    {tab === 'production' && <Card title={L(locale, 'What remains before the final production patch', 'المتبقي قبل تحديث الإنتاج النهائي')} icon={<Database/>}><Table rows={[{ area: 'Backend', missing: 'Real Supabase Auth/RLS wiring and smoke tests', priority: 'Critical' }, { area: 'Posting', missing: 'Server-side posting orchestrator connected to frontend actions', priority: 'Critical' }, { area: 'Storage', missing: 'Attachment upload to Supabase buckets', priority: 'High' }, { area: 'Refactor', missing: 'Split large App.tsx into setup/inventory/finance modules', priority: 'High' }, { area: 'Pilot', missing: 'End-to-end branch pilot using real Foodics files and signed close report', priority: 'Critical' }]}/></Card>}
    {tab === 'final-notes' && <Card title={L(locale, 'Pre-final notes', 'ملاحظات ما قبل النهائي')} icon={<AlertTriangle/>}><Table rows={notes}/></Card>}
    {tab === 'actions' && <Card title={L(locale, 'Safe local release actions', 'إجراءات إطلاق محلية آمنة')} icon={<Wrench/>}><div className="button-row"><button onClick={ensureFinalPilot}><Sparkles size={16}/>{L(locale, 'Ensure pre-final controls', 'تجهيز ضوابط ما قبل النهائي')}</button><button onClick={logReview}><ClipboardCheck size={16}/>{L(locale, 'Log pre-final review', 'تسجيل مراجعة ما قبل النهائي')}</button><button onClick={() => downloadJson('v299_pre_final_diagnostics.json', snapshot)}><Download size={16}/>{L(locale, 'Export diagnostics', 'تصدير التشخيص')}</button></div></Card>}
  </div>;
}
function tabLabel(tab: Tab, locale: Locale) { const labels: Record<Tab, [string, string]> = { command: ['Command', 'القيادة'], gates: ['Release Gates', 'بوابات الإطلاق'], scorecard: ['Scorecard', 'التقييم'], regression: ['Regression', 'الاختبارات'], issues: ['Issues', 'المشاكل'], production: ['Before Final', 'قبل النهائي'], 'final-notes': ['Notes', 'ملاحظات'], actions: ['Actions', 'إجراءات'] }; return L(locale, labels[tab][0], labels[tab][1]); }
