import { useMemo, useState } from 'react';
import { AlertTriangle, BadgeCheck, BarChart3, BrainCircuit, ClipboardCheck, CloudCog, Database, Download, Factory, FileCheck2, FileText, GitBranch, Landmark, Layers, LockKeyhole, PackageCheck, ReceiptText, ShieldCheck, Sparkles, Store, WalletCards, XCircle } from 'lucide-react';
import { buildV120BackendSchema, buildV120Program, buildV120QaSuite, buildV120Readiness, buildV120ReportFactory, buildV120ScoreNotes, downloadCsv, money } from '../engines/enterpriseV120Engine';

type Locale = 'en' | 'ar';
type TabKey = 'command' | 'program' | 'backend' | 'posting' | 'foodics' | 'inventory' | 'finance' | 'procurement' | 'production' | 'reports' | 'governance' | 'qa' | 'notes';
type Props = { state: any; totals: any; update?: (fn: (current: any) => any, success?: string) => void; locale: Locale; notify?: (type: 'success' | 'warning' | 'error', message: string) => void };
function L(locale: Locale, en: string, ar: string) { return locale === 'ar' ? ar : en; }
function today() { return new Date().toISOString().slice(0, 10); }
function id(prefix: string) { return `${prefix}-${Math.random().toString(36).slice(2, 10)}`; }
function Pill({ tone, children }: { tone: 'good' | 'warn' | 'bad' | 'info'; children: React.ReactNode }) { return <span className={`pill ${tone}`}>{children}</span>; }
function Card({ title, icon, action, children }: { title: string; icon?: React.ReactNode; action?: React.ReactNode; children: React.ReactNode }) { return <section className="card"><div className="card-header"><div className="card-title">{icon}{title}</div>{action}</div>{children}</section>; }
function Kpi({ label, value, hint, icon, tone = 'info' }: { label: string; value: string | number; hint: string; icon: React.ReactNode; tone?: 'good' | 'warn' | 'bad' | 'info' }) { return <div className={`kpi-card ${tone}`}><div className="kpi-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div></div>; }
function Table({ headers, rows }: { headers: React.ReactNode[]; rows: React.ReactNode[][] }) { return <div className="table-wrap"><table><thead><tr>{headers.map((h, index) => <th key={index}>{h}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, r) => <tr key={r}>{row.map((cell, c) => <td key={c}>{cell}</td>)}</tr>) : <tr><td colSpan={headers.length} className="muted">No rows</td></tr>}</tbody></table></div>; }
function statusTone(value: string): 'good' | 'warn' | 'bad' | 'info' { const lower = value.toLowerCase(); if (lower.includes('critical') || lower.includes('bad') || lower.includes('missing') || lower.includes('blocked')) return 'bad'; if (lower.includes('high') || lower.includes('warn') || lower.includes('partial')) return 'warn'; if (lower.includes('ready') || lower.includes('good') || lower.includes('complete')) return 'good'; return 'info'; }

export default function EnterpriseV120Page({ state, totals, update, locale, notify }: Props) {
  const [tab, setTab] = useState<TabKey>('command');
  const [period, setPeriod] = useState(today().slice(0, 7));
  const readiness = useMemo(() => buildV120Readiness(state, totals), [state, totals]);
  const program = useMemo(() => buildV120Program(), []);
  const backendSchema = useMemo(() => buildV120BackendSchema(), []);
  const qaSuite = useMemo(() => buildV120QaSuite(), []);
  const reports = useMemo(() => buildV120ReportFactory(), []);
  const scoreNotes = useMemo(() => buildV120ScoreNotes(), []);
  const tabs: { key: TabKey; en: string; ar: string; icon: React.ReactNode }[] = [
    { key: 'command', en: 'Command', ar: 'القيادة', icon: <Sparkles size={16}/> }, { key: 'program', en: 'v101-v120 Program', ar: 'برنامج v101-v120', icon: <GitBranch size={16}/> }, { key: 'backend', en: 'Backend', ar: 'الخلفية', icon: <Database size={16}/> }, { key: 'posting', en: 'Posting Guard', ar: 'حارس الترحيل', icon: <LockKeyhole size={16}/> }, { key: 'foodics', en: 'Foodics', ar: 'فودكس', icon: <ReceiptText size={16}/> }, { key: 'inventory', en: 'Inventory', ar: 'المخزون', icon: <Store size={16}/> }, { key: 'finance', en: 'Finance', ar: 'المالية', icon: <Landmark size={16}/> }, { key: 'procurement', en: 'Procurement', ar: 'المشتريات', icon: <PackageCheck size={16}/> }, { key: 'production', en: 'Production', ar: 'الإنتاج', icon: <Factory size={16}/> }, { key: 'reports', en: 'Reports', ar: 'التقارير', icon: <BarChart3 size={16}/> }, { key: 'governance', en: 'Governance', ar: 'الحوكمة', icon: <ShieldCheck size={16}/> }, { key: 'qa', en: 'QA', ar: 'الاختبار', icon: <ClipboardCheck size={16}/> }, { key: 'notes', en: 'Score Notes', ar: 'التقييم', icon: <BrainCircuit size={16}/> },
  ];
  const exportReadiness = () => downloadCsv(`v120_enterprise_readiness_${period}.csv`, readiness.checks.map((c: any) => ({ period, area: c.area, title: c.title, status: c.status, score: c.score, evidence: c.evidence, action: c.action })));
  const exportQa = () => downloadCsv(`v120_qa_suite_${period}.csv`, qaSuite);
  const exportBackend = () => downloadCsv(`v120_backend_schema_${period}.csv`, backendSchema);
  const exportProgram = () => downloadCsv(`v120_program_${period}.csv`, program);
  const logV120Review = () => { if (!update) return; update((current: any) => ({ ...current, auditLogs: [ ...(Array.isArray(current.auditLogs) ? current.auditLogs : []), { id: id('AUD'), at: new Date().toISOString(), action: 'v120_health_review', entity: 'enterprise_v120', ref: period, user: 'Local Admin', note: `v120 readiness ${readiness.readinessScore}/100, production ${readiness.productionScore}/100` }, ], }), L(locale, 'v120 health review logged.', 'تم تسجيل مراجعة v120.')); notify?.('success', L(locale, 'v120 health review logged.', 'تم تسجيل مراجعة v120.')); };
  return <div className="page-grid enterprise-v120">
    <Card title={L(locale, 'Enterprise v120 production-readiness cockpit', 'غرفة جاهزية الإنتاج v120')} icon={<Sparkles/>} action={<div className="button-row compact"><input type="month" value={period} onChange={(e) => setPeriod(e.target.value)}/><button onClick={exportReadiness}><Download size={14}/>{L(locale, 'Readiness', 'الجاهزية')}</button><button onClick={exportProgram}><Download size={14}/>{L(locale, 'Program', 'البرنامج')}</button><button onClick={exportQa}><Download size={14}/>{L(locale, 'QA', 'الاختبار')}</button></div>}>
      <div className="kpi-grid"><Kpi label={L(locale, 'Readiness', 'الجاهزية')} value={`${readiness.readinessScore}/100`} hint={L(locale, 'Local control score', 'مؤشر الرقابة المحلي')} icon={<BadgeCheck/>} tone={readiness.readinessScore >= 75 ? 'good' : readiness.readinessScore >= 55 ? 'warn' : 'bad'}/><Kpi label={L(locale, 'Production', 'الإنتاجية الفعلية')} value={`${readiness.productionScore}/100`} hint={L(locale, 'Still limited by local-first mode', 'ما زال محدودًا لأنه محلي')} icon={<CloudCog/>} tone="warn"/><Kpi label={L(locale, 'Critical blockers', 'عوائق حرجة')} value={readiness.critical.length} hint={L(locale, 'Must fix before live use', 'يجب حلها قبل التشغيل')} icon={<XCircle/>} tone={readiness.critical.length ? 'bad' : 'good'}/><Kpi label={L(locale, 'Inventory value', 'قيمة المخزون')} value={money(readiness.stockValue)} hint={L(locale, 'From local movements', 'من حركات المخزون المحلية')} icon={<Store/>} tone="info"/><Kpi label={L(locale, 'AP exposure', 'التزامات الموردين')} value={money(readiness.apExposure)} hint={L(locale, 'Supplier liability view', 'عرض التزامات الموردين')} icon={<WalletCards/>} tone="info"/><Kpi label={L(locale, 'Backend score', 'تقييم الخلفية')} value={`${readiness.backendScore}/100`} hint={L(locale, 'Blueprint exists; implementation next', 'المخطط موجود والتنفيذ التالي')} icon={<Database/>} tone="bad"/></div>
    </Card>
    <div className="tabs">{tabs.map((item) => <button key={item.key} className={tab === item.key ? 'active-tab' : ''} onClick={() => setTab(item.key)}>{item.icon}{L(locale, item.en, item.ar)}</button>)}</div>
    {tab === 'command' && <div className="page-grid two"><Card title={L(locale, 'Priority board', 'لوحة الأولويات')} icon={<AlertTriangle/>} action={<button onClick={logV120Review}><FileCheck2 size={14}/>{L(locale, 'Log review', 'تسجيل مراجعة')}</button>}><Table headers={[L(locale, 'Area', 'المجال'), L(locale, 'Status', 'الحالة'), L(locale, 'Evidence', 'الدليل'), L(locale, 'Action', 'الإجراء')]} rows={readiness.checks.map((c: any) => [c.area, <Pill tone={c.status}>{c.title}</Pill>, c.evidence, c.action])}/></Card><Card title={L(locale, 'Operating snapshot', 'لقطة تشغيلية')} icon={<Layers/>}><Table headers={[L(locale, 'Metric', 'المؤشر'), L(locale, 'Value', 'القيمة')]} rows={Object.entries(readiness.counts).map(([k, v]) => [k, String(v)])}/></Card></div>}
    {tab === 'program' && <Card title={L(locale, 'Combined v101-v120 enterprise program', 'برنامج المؤسسة المدمج v101-v120')} icon={<GitBranch/>}><Table headers={['Version', 'Theme', 'Deliverable', 'Status']} rows={program.map((row) => [row.version, row.theme, row.deliverable, <Pill tone={statusTone(row.status)}>{row.status}</Pill>])}/></Card>}
    {tab === 'backend' && <div className="page-grid two"><Card title={L(locale, 'Backend schema domains', 'مجالات قاعدة البيانات')} icon={<Database/>} action={<button onClick={exportBackend}><Download size={14}/>{L(locale, 'Export', 'تصدير')}</button>}><Table headers={['Domain', 'Objects', 'Owner', 'Priority']} rows={backendSchema.map((row) => [row.domain, row.object, row.owner, <Pill tone={statusTone(row.priority)}>{row.priority}</Pill>])}/></Card><Card title={L(locale, 'Production backend note', 'ملاحظة الخلفية الإنتاجية')} icon={<CloudCog/>}><div className="notice"><strong>{L(locale, 'Honest status:', 'الوضع الحقيقي:')}</strong> {L(locale, 'v120 is still a local enterprise prototype. The next real milestone is Supabase Auth + PostgreSQL + RLS + server-side posting functions.', 'لا يزال v120 نموذجًا محليًا مؤسسيًا. المرحلة الحقيقية التالية هي Supabase Auth + PostgreSQL + RLS + دوال ترحيل على الخادم.')}</div><ul className="check-list"><li>{L(locale, 'Auth and tenant isolation', 'المصادقة وعزل الشركة')}</li><li>{L(locale, 'RLS for branch/store/cost center security', 'سياسات RLS لأمن الفروع والمخازن ومراكز التكلفة')}</li><li>{L(locale, 'Edge Functions for posting and reversal', 'دوال Edge للترحيل والعكس')}</li><li>{L(locale, 'Storage buckets for attachments', 'حاويات تخزين للمرفقات')}</li><li>{L(locale, 'Audit triggers and backup strategy', 'مشغلات تدقيق وخطة نسخ احتياطي')}</li></ul></Card></div>}
    {tab === 'posting' && <Card title={L(locale, 'Central posting guard target', 'هدف حارس الترحيل المركزي')} icon={<LockKeyhole/>}><div className="timeline"><span>Validate</span><span>Permission</span><span>Period</span><span>Lifecycle</span><span>Inventory</span><span>GL</span><span>Audit</span><span>Status</span></div><Table headers={['Posting flow', 'Required guard', 'Current local status']} rows={[['Foodics Full ERP', 'mapping + recipes + stock + cost + period + approval', 'Prototype flow exists; backend enforcement missing'], ['Sales Accounting Only', 'branch/payment mapping + VAT + period + approval', 'Good starter mode; settlement needs backend'], ['Opening Stock', 'item/store/cost + approval + locked period check', 'Local upload exists'], ['Monthly Count Variance', 'variance approval + cost + period lock', 'Local approval flow exists'], ['Supplier Payment', 'invoice allocation + AP balance + bank account + approval', 'Prototype allocation exists'], ['Manual Journal', 'balanced batch + approval + attachments + period', 'Manual journal exists; attachments/approval missing'], ['Production Batch', 'recipe + raw stock + output + traceability + approval', 'Concept exists; traceability missing']].map((row) => row)}/></Card>}
    {tab === 'foodics' && <div className="page-grid two"><Card title={L(locale, 'Foodics close and settlement readiness', 'جاهزية إغلاق وتسوية فودكس')} icon={<ReceiptText/>}><Table headers={['Control', 'Current status', 'Next']} rows={[['Menu/products import', 'Native Foodics import + SKU mapping exists', 'Persist mappings in backend'], ['Sales headers/lines/payments', 'Upload/validation/issue center exists', 'Staging tables + duplicate hash'], ['Report only mode', 'Supported', 'Add official approval status'], ['Sales accounting only', 'Supported', 'Add settlement workbench'], ['Full ERP posting', 'Supported with recipe/stock controls', 'Server-side posting + reversal'], ['Voids/returns/discounts', 'Control page exists', 'Detailed reports + VAT treatment audit'], ['Payment settlement', 'Design exists', 'MADA/card/delivery app settlement workflow']].map((row) => row)}/></Card><Card title={L(locale, 'Foodics batch exposure', 'تعرض دفعات فودكس')} icon={<FileText/>}><Table headers={['Metric', 'Value']} rows={[[L(locale, 'Batches/history rows', 'دفعات/سجل'), readiness.foodicsBatches.length], [L(locale, 'Posted-like batches', 'دفعات مرحلة'), readiness.foodicsPosted.length], [L(locale, 'Missing recipes', 'وصفات ناقصة'), readiness.missingRecipes.length], [L(locale, 'Zero-cost stock rows', 'مخزون بتكلفة صفرية'), readiness.zeroCostStock.length]]}/></Card></div>}
    {tab === 'inventory' && <div className="page-grid two"><Card title={L(locale, 'Inventory risk board', 'لوحة مخاطر المخزون')} icon={<Store/>}><Table headers={['Risk', 'Count', 'Policy']} rows={[['Negative stock', readiness.negativeStock.length, 'Block posting or require approved correction'], ['Zero-cost stock', readiness.zeroCostStock.length, 'Require purchase/opening cost before COGS'], ['Pending count approvals', readiness.pendingInventoryApprovals.length, 'Approve/reject before close'], ['Stock movement rows', readiness.counts.stockMovements, 'Must reconcile to GL inventory']].map((row) => row)}/></Card><Card title={L(locale, 'Top stock value rows', 'أعلى أرصدة مخزنية')} icon={<BarChart3/>}><Table headers={['Store', 'Item', 'Qty', 'Value']} rows={readiness.stockRows.slice().sort((a: any,b: any) => Math.abs(b.value)-Math.abs(a.value)).slice(0, 12).map((row: any) => [row.storeName, row.itemName, row.qty.toFixed(2), money(row.value)])}/></Card></div>}
    {tab === 'finance' && <div className="page-grid two"><Card title={L(locale, 'CFO close controls', 'ضوابط إغلاق المدير المالي')} icon={<Landmark/>}><Table headers={['Control', 'Evidence', 'Required next']} rows={[['Journal balance', `Debit ${money(readiness.debit)} / Credit ${money(readiness.credit)} / Diff ${money(readiness.journalDiff)}`, 'Block close if diff > 0'], ['AP exposure', money(readiness.apExposure), 'Add AP aging and payment schedule'], ['Bank unmatched', String(readiness.unmatchedBank.length), 'Add bank matching rules'], ['Fiscal periods', String(readiness.counts.fiscalPeriods), 'Enforce period lock across all modules'], ['Posted journals', String(readiness.counts.journals), 'Add approval + attachment register']].map((row) => row)}/></Card><Card title={L(locale, 'Finance professional gaps', 'فجوات مالية احترافية')} icon={<WalletCards/>}><ul className="check-list"><li>Journal approval workflow</li><li>Receipt/payment voucher registers</li><li>AP/AR aging deep reports</li><li>Bank reconciliation matching rules</li><li>Fixed asset disposal and depreciation batch</li><li>Excel/PDF financial statements</li></ul></Card></div>}
    {tab === 'procurement' && <Card title={L(locale, 'Procurement enterprise controls', 'ضوابط مشتريات مؤسسية')} icon={<PackageCheck/>}><Table headers={['Control', 'Current local evidence', 'Enterprise requirement']} rows={[['Material request', `${readiness.counts.purchaseOrders} POs / ${readiness.counts.goodsReceipts} GRNs`, 'Add PR and quotation comparison'], ['PO to GRN', 'GRN concept exists', 'Partial receiving + backorder'], ['GRN to invoice', 'GRNI design exists', 'Line-level variance enforcement'], ['Supplier payment', `${readiness.counts.supplierPayments} payments`, 'Multi-invoice allocation and approval'], ['Supplier compliance', `${readiness.suppliersMissingCompliance.length} suppliers missing compliance fields`, 'Block payment until supplier master complete']].map((row) => row)}/></Card>}
    {tab === 'production' && <Card title={L(locale, 'Production/prep kitchen traceability roadmap', 'خارطة تتبع الإنتاج والتحضير')} icon={<Factory/>}><Table headers={['Layer', 'Current', 'Next enterprise behavior']} rows={[['Production recipes', `${readiness.counts.productionRecipes ?? 'local data'} recipe foundation`, 'Version/approve/effective date'], ['Production batches', 'Batch posting concept exists', 'Draft → approved → posted → reversed'], ['Lot traceability', 'Lots exist in inventory concept', 'Raw lot → produced lot → final sale'], ['Yield variance', 'Costing concept exists', 'Planned vs actual ingredients/output'], ['Expiry', 'Expiry fields exist', 'Produced batch expiry + FEFO consumption']].map((row) => row)}/></Card>}
    {tab === 'reports' && <div className="page-grid two"><Card title={L(locale, 'Board report factory', 'مصنع تقارير الإدارة')} icon={<BarChart3/>} action={<button onClick={() => downloadCsv(`v120_report_factory_${period}.csv`, reports)}><Download size={14}/>{L(locale, 'Export', 'تصدير')}</button>}><Table headers={['Report', 'Format', 'Sections']} rows={reports.map((r) => [r.report, r.format, r.sections])}/></Card><Card title={L(locale, 'Report gaps to close', 'فجوات التقارير')} icon={<FileText/>}><ul className="check-list"><li>Board-ready PDF pack</li><li>Formatted Excel reports</li><li>Branch P&L by month</li><li>Theoretical vs actual trend</li><li>Sales by hour/cashier/category/payment</li><li>AP/AR aging and cash forecast</li></ul></Card></div>}
    {tab === 'governance' && <Card title={L(locale, 'Governance and data-quality controls', 'حوكمة وجودة البيانات')} icon={<ShieldCheck/>}><Table headers={['Area', 'Status', 'Evidence', 'Action']} rows={readiness.checks.filter((c: any) => ['Data Quality','Suppliers','Backend','People'].includes(c.area)).map((c: any) => [c.area, <Pill tone={c.status}>{c.title}</Pill>, c.evidence, c.action])}/></Card>}
    {tab === 'qa' && <Card title={L(locale, 'v120 QA regression suite', 'حزمة اختبارات v120')} icon={<ClipboardCheck/>} action={<button onClick={exportQa}><Download size={14}/>{L(locale, 'Export QA', 'تصدير الاختبار')}</button>}><Table headers={['Flow', 'Test', 'Expected']} rows={qaSuite.map((row) => [row.flow, row.test, row.expected])}/></Card>}
    {tab === 'notes' && <Card title={L(locale, 'Current v120 score notes', 'ملاحظات تقييم v120')} icon={<BrainCircuit/>}><Table headers={['Score', 'Value', 'Note']} rows={scoreNotes.map((row) => [row.score, <strong>{row.value}</strong>, row.note])}/><div className="notice"><strong>{L(locale, 'Next serious milestone:', 'المرحلة الجادة التالية:')}</strong> {L(locale, 'v121 Supabase Backend Foundation. Stop adding local dashboards; begin real persistence, Auth, RLS, Edge Functions, audit and storage.', 'v121 تأسيس خلفية Supabase. أوقف إضافة لوحات محلية وابدأ الحفظ الحقيقي والمصادقة وسياسات RLS ودوال الخادم والتدقيق والتخزين.')}</div></Card>}
  </div>;
}
