import { useMemo, useState } from 'react';
import { AlertTriangle, BadgeCheck, BrainCircuit, ClipboardCheck, CloudCog, Database, Download, FileCheck2, FileCode2, GitBranch, Layers, LockKeyhole, PlayCircle, Rocket, ShieldCheck, Sparkles, UploadCloud } from 'lucide-react';
import { buildV130ApiContracts, buildV130BackendDomains, buildV130Command, buildV130CutoverPlan, buildV130Program, buildV130QaSuite, buildV130Scores, downloadCsv, money, pct } from '../engines/enterpriseV130Engine';

type Locale = 'en' | 'ar';
type Tab = 'command' | 'program' | 'backend' | 'contracts' | 'cutover' | 'guard' | 'qa' | 'scores';
type Props = { state: any; totals: any; update?: (fn: (current: any) => any, success?: string) => void; locale: Locale; notify?: (type: 'success' | 'warning' | 'error', message: string) => void };
function L(locale: Locale, en: string, ar: string) { return locale === 'ar' ? ar : en; }
function todayMonth() { return new Date().toISOString().slice(0, 7); }
function id(prefix: string) { return `${prefix}-${Math.random().toString(36).slice(2, 10)}`; }
function Pill({ tone, children }: { tone: 'good' | 'warn' | 'bad' | 'info'; children: React.ReactNode }) { return <span className={`pill ${tone}`}>{children}</span>; }
function Card({ title, icon, action, children }: { title: string; icon?: React.ReactNode; action?: React.ReactNode; children: React.ReactNode }) { return <section className="card"><div className="card-header"><div className="card-title">{icon}{title}</div>{action}</div>{children}</section>; }
function Kpi({ label, value, hint, icon, tone = 'info' }: { label: string; value: string | number; hint: string; icon: React.ReactNode; tone?: 'good' | 'warn' | 'bad' | 'info' }) { return <div className={`kpi-card ${tone}`}><div className="kpi-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div></div>; }
function Table({ headers, rows }: { headers: React.ReactNode[]; rows: React.ReactNode[][] }) { return <div className="table-wrap"><table><thead><tr>{headers.map((h, index) => <th key={index}>{h}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, r) => <tr key={r}>{row.map((cell, c) => <td key={c}>{cell}</td>)}</tr>) : <tr><td colSpan={headers.length} className="muted">No rows</td></tr>}</tbody></table></div>; }
function toneFromStatus(value: string): 'good' | 'warn' | 'bad' | 'info' { const v = String(value).toLowerCase(); if (v.includes('critical') || v.includes('block') || v.includes('missing')) return 'bad'; if (v.includes('designed') || v.includes('planned') || v.includes('warn') || v.includes('partial')) return 'warn'; if (v.includes('ready') || v.includes('included') || v.includes('clean')) return 'good'; return 'info'; }

export default function EnterpriseV130Page({ state, totals, update, locale, notify }: Props) {
  const [tab, setTab] = useState<Tab>('command');
  const [period, setPeriod] = useState(todayMonth());
  const command = useMemo(() => buildV130Command(state, totals), [state, totals]);
  const program = useMemo(() => buildV130Program(), []);
  const backend = useMemo(() => buildV130BackendDomains(), []);
  const contracts = useMemo(() => buildV130ApiContracts(), []);
  const cutover = useMemo(() => buildV130CutoverPlan(), []);
  const qa = useMemo(() => buildV130QaSuite(), []);
  const scores = useMemo(() => buildV130Scores(), []);
  const tabs: { key: Tab; en: string; ar: string; icon: React.ReactNode }[] = [
    { key: 'command', en: 'Command', ar: 'القيادة', icon: <Rocket size={16}/> },
    { key: 'program', en: 'v122-v130 Program', ar: 'برنامج v122-v130', icon: <GitBranch size={16}/> },
    { key: 'backend', en: 'Backend Domains', ar: 'مجالات الخلفية', icon: <Database size={16}/> },
    { key: 'contracts', en: 'API Contracts', ar: 'عقود API', icon: <FileCode2 size={16}/> },
    { key: 'cutover', en: 'Cutover', ar: 'الانتقال', icon: <PlayCircle size={16}/> },
    { key: 'guard', en: 'Posting Guard', ar: 'حارس الترحيل', icon: <ShieldCheck size={16}/> },
    { key: 'qa', en: 'QA Suite', ar: 'اختبارات الجودة', icon: <ClipboardCheck size={16}/> },
    { key: 'scores', en: 'Scores & Notes', ar: 'التقييم والملاحظات', icon: <BrainCircuit size={16}/> },
  ];
  const exportReadiness = () => downloadCsv(`v130_enterprise_readiness_${period}.csv`, command.checks.map((row: any) => ({ period, area: row.area, control: row.control, status: row.status, tone: row.tone, evidence: row.evidence, next: row.next })));
  const exportProgram = () => downloadCsv(`v130_program_${period}.csv`, program);
  const exportBackend = () => downloadCsv(`v130_backend_domains_${period}.csv`, backend);
  const exportContracts = () => downloadCsv(`v130_api_contracts_${period}.csv`, contracts);
  const exportCutover = () => downloadCsv(`v130_cutover_plan_${period}.csv`, cutover);
  const exportQa = () => downloadCsv(`v130_qa_suite_${period}.csv`, qa);
  const logReview = () => { if (!update) return; update((current: any) => ({ ...current, auditLogs: [...(Array.isArray(current.auditLogs) ? current.auditLogs : []), { id: id('AUD'), at: new Date().toISOString(), action: 'v130_backend_cutover_review', entity: 'enterprise_v130', ref: period, user: 'Local Admin', note: `v130 backend score ${command.backendScore}/100, production ${command.productionScore}/100, blockers ${command.blockers.length}` }] }), L(locale, 'v130 backend/cutover review logged.', 'تم تسجيل مراجعة v130 للخلفية والانتقال.')); notify?.('success', L(locale, 'v130 review logged.', 'تم تسجيل مراجعة v130.')); };
  return <div className="page-grid enterprise-v130">
    <Card title={L(locale, 'v130 Backend cutover command center', 'v130 مركز قيادة الخلفية والانتقال')} icon={<Rocket/>} action={<div className="button-row compact"><input type="month" value={period} onChange={(e) => setPeriod(e.target.value)}/><button onClick={exportReadiness}><Download size={14}/>{L(locale, 'Readiness', 'الجاهزية')}</button><button onClick={exportQa}><Download size={14}/>{L(locale, 'QA', 'الاختبار')}</button></div>}>
      <div className="kpi-grid"><Kpi label={L(locale, 'Local MVP', 'النموذج المحلي')} value={pct(command.localScore)} hint={L(locale, 'Workflow demo readiness', 'جاهزية تجربة التدفقات')} icon={<Sparkles/>} tone="good"/><Kpi label={L(locale, 'ERP foundation', 'أساس ERP')} value={pct(command.foundationScore)} hint={L(locale, 'Architecture direction', 'اتجاه البنية')} icon={<BadgeCheck/>} tone="good"/><Kpi label={L(locale, 'Backend readiness', 'جاهزية الخلفية')} value={pct(command.backendScore)} hint={L(locale, 'v130 migration depth', 'عمق ترحيل v130')} icon={<CloudCog/>} tone="warn"/><Kpi label={L(locale, 'Production readiness', 'جاهزية الإنتاج')} value={pct(command.productionScore)} hint={L(locale, 'Needs wiring and testing', 'تحتاج ربط واختبار')} icon={<LockKeyhole/>} tone="warn"/><Kpi label={L(locale, 'Blockers', 'العوائق')} value={command.blockers.length} hint={L(locale, 'Must fix before go-live', 'يجب حلها قبل التشغيل')} icon={<AlertTriangle/>} tone={command.blockers.length ? 'bad' : 'good'}/><Kpi label={L(locale, 'Inventory value', 'قيمة المخزون')} value={money(command.totals.inventory)} hint={L(locale, 'Local stock ledger', 'سجل المخزون المحلي')} icon={<Layers/>} tone="info"/></div>
    </Card>
    <div className="tabs">{tabs.map((item) => <button key={item.key} className={tab === item.key ? 'active-tab' : ''} onClick={() => setTab(item.key)}>{item.icon}{L(locale, item.en, item.ar)}</button>)}</div>
    {tab === 'command' && <div className="page-grid two"><Card title={L(locale, 'Enterprise readiness board', 'لوحة جاهزية المؤسسة')} icon={<FileCheck2/>} action={<button onClick={logReview}><FileCheck2 size={14}/>{L(locale, 'Log review', 'تسجيل مراجعة')}</button>}><Table headers={[L(locale, 'Area', 'المجال'), L(locale, 'Control', 'الضابط'), L(locale, 'Status', 'الحالة'), L(locale, 'Evidence', 'الدليل'), L(locale, 'Next', 'التالي')]} rows={command.checks.map((c: any) => [c.area, c.control, <Pill tone={c.tone}>{c.status}</Pill>, c.evidence, c.next])}/></Card><Card title={L(locale, 'Operating snapshot', 'لقطة التشغيل')} icon={<Database/>}><Table headers={[L(locale, 'Metric', 'المؤشر'), L(locale, 'Value', 'القيمة')]} rows={Object.entries(command.counts).map(([key, value]) => [key, String(value)])}/><div className="notice">{L(locale, 'v130 is still a backend-readiness and cutover package. The next value is wiring setup/Foodics/inventory posting to Supabase tables and Edge Functions.', 'v130 لا يزال حزمة جاهزية خلفية وانتقال. القيمة التالية هي ربط الإعدادات وفودكس وترحيل المخزون بجداول Supabase ودوال Edge.')}</div></Card></div>}
    {tab === 'program' && <Card title={L(locale, 'Combined v122-v130 backend program', 'برنامج الخلفية المدمج v122-v130')} icon={<GitBranch/>} action={<button onClick={exportProgram}><Download size={14}/>{L(locale, 'Export', 'تصدير')}</button>}><Table headers={['Version', 'Theme', 'Outcome', 'Status', 'Priority']} rows={program.map((row) => [row.version, row.theme, row.outcome, <Pill tone={toneFromStatus(row.status)}>{row.status}</Pill>, <Pill tone={toneFromStatus(row.priority)}>{row.priority}</Pill>])}/></Card>}
    {tab === 'backend' && <Card title={L(locale, 'Backend schema and function domains', 'مجالات الجداول والدوال في الخلفية')} icon={<Database/>} action={<button onClick={exportBackend}><Download size={14}/>{L(locale, 'Export', 'تصدير')}</button>}><Table headers={['Domain', 'Tables', 'Functions', 'Readiness']} rows={backend.map((row) => [row.domain, row.tables, row.functions, <Pill tone={toneFromStatus(row.readiness)}>{row.readiness}</Pill>])}/></Card>}
    {tab === 'contracts' && <Card title={L(locale, 'Production API contracts', 'عقود API للإنتاج')} icon={<FileCode2/>} action={<button onClick={exportContracts}><Download size={14}/>{L(locale, 'Export', 'تصدير')}</button>}><Table headers={['Endpoint', 'Payload', 'Result', 'Guard']} rows={contracts.map((row) => [row.endpoint, row.payload, row.result, row.guard])}/></Card>}
    {tab === 'cutover' && <Card title={L(locale, 'Go-live cutover plan', 'خطة الانتقال للتشغيل')} icon={<PlayCircle/>} action={<button onClick={exportCutover}><Download size={14}/>{L(locale, 'Export', 'تصدير')}</button>}><Table headers={['Wave', 'Name', 'Objective', 'Exit Criteria']} rows={cutover.map((row) => [row.wave, row.name, row.objective, row.exitCriteria])}/></Card>}
    {tab === 'guard' && <div className="page-grid two"><Card title={L(locale, 'Central posting guard requirements', 'متطلبات حارس الترحيل المركزي')} icon={<ShieldCheck/>}><Table headers={[L(locale, 'Step', 'الخطوة'), L(locale, 'Requirement', 'المتطلب')]} rows={['Validate source document and duplicate key', 'Check permission and branch/store/cost-center scope', 'Check fiscal period is open', 'Check document lifecycle status', 'Create inventory movement if needed', 'Create balanced GL journal if needed', 'Write immutable audit and posting event', 'Update source document status'].map((row, index) => [String(index + 1), row])}/></Card><Card title={L(locale, 'Current local risk notes', 'ملاحظات المخاطر المحلية')} icon={<AlertTriangle/>}><Table headers={['Risk', 'Count / Value']} rows={[[L(locale, 'Negative stock rows', 'صفوف مخزون سالبة'), command.negativeStock.length], [L(locale, 'Zero-cost positive stock', 'مخزون موجب بدون تكلفة'), command.zeroCostPositive.length], [L(locale, 'Supplier compliance gaps', 'نواقص امتثال الموردين'), command.missingSupplierCompliance.length], [L(locale, 'Journal debit', 'مدين القيود'), command.debit.toFixed(2)], [L(locale, 'Journal credit', 'دائن القيود'), command.credit.toFixed(2)]]}/></Card></div>}
    {tab === 'qa' && <Card title={L(locale, 'v130 QA regression suite', 'حزمة اختبارات v130')} icon={<ClipboardCheck/>} action={<button onClick={exportQa}><Download size={14}/>{L(locale, 'Export QA', 'تصدير الاختبار')}</button>}><Table headers={['Area', 'Test', 'Expected']} rows={qa.map((row) => [row.area, row.test, row.expected])}/></Card>}
    {tab === 'scores' && <div className="page-grid two"><Card title={L(locale, 'Current scores after v130', 'التقييم الحالي بعد v130')} icon={<BrainCircuit/>}><Table headers={['View', 'Score', 'Note']} rows={scores.map((row) => [row.view, row.score, row.note])}/></Card><Card title={L(locale, 'Next recommended milestone', 'المعلم التالي المقترح')} icon={<UploadCloud/>}><div className="notice"><strong>v131 — Auth + Setup Persistence</strong><br/>{L(locale, 'Connect company, login, branches, stores, suppliers, items, chart of accounts and cost centers to Supabase with local fallback. This is the first real production wiring step.', 'ربط الشركة وتسجيل الدخول والفروع والمخازن والموردين والأصناف ودليل الحسابات ومراكز التكلفة مع Supabase مع استمرار الوضع المحلي كخطة احتياطية. هذه أول خطوة ربط إنتاجية حقيقية.')}</div><button onClick={exportReadiness}><Download size={14}/>{L(locale, 'Export v130 readiness', 'تصدير جاهزية v130')}</button></Card></div>}
  </div>;
}
